# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c436bcc6cc418d5fac16bb56031d6a613ff6586ce7a7481542492ff9e26f078ffdcddf642ef25bbe27a02f1a1be30c631faafaaed2e756687cfcaa58f59fdb07

test:
  secret_key_base: 9a84e2d3e95c981f8aaf157d2c122c5acbbdb0b33a3178fe8ff9ac96a5f0224718d2763dac8873a1b7a2c9cea4b3306a2546225568edd757319eb7f5ad3cb78d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
